### Site metadata ###

title: Dev Cheatsheets
description: A collection of code snippets and CLI guides for quick and easy reference while coding

github_username: MichaelCurrin

### Build settings ###

url: "https://michaelcurrin.github.io"
baseurl: "/dev-cheatsheets"

google_analytics: UA-87705880-12

header_pages:
  - index.md
  - cheatsheets/index.md
  - about.md

exclude:
  - docs/
  - vendor/
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Makefile
  - README.md

liquid:
  error_mode: strict

### Theme boilerplate ###

remote_theme: MichaelCurrin/fractal

titles_from_headings:
  strip_title: true

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
